[package]
name = "rust-getopts-test"
version = "0.1.0"
authors = ["Silvio Fricke <silvio.fricke@gmail.com>"]

[dependencies.getopts]
version = "*"
git = "https://github.com/silvio/rust-getopts.git"
branch = "sfr/Optiongroup-and-friends"
